import React, {Component} from 'react'
import {
  View,
  Text,
  SafeAreaView,
  StatusBar,
  TouchableOpacity,
  FlatList,
  Image,
  TextInput,
  Picker,
  TimePickerAndroid,
} from 'react-native'
import Fonts from '../Theme/CustomeFonts'
import Colors from '../Theme/Colors'
import FloatingButton from '../Components/FloatingButton'
import Style from '../Theme/Style'
import Icon from 'react-native-vector-icons/FontAwesome'
import AppImages from '../Theme/image'
import Header from '../Components/Header'
import {DatePicker, Col} from 'native-base'
import { ScrollView } from 'react-native'

class ReportView extends Component {
 
  static navigationOptions = ({ navigation }) => {
    return {
        title: 'Report',
        headerTitleStyle: {
            width: '100%',
           
            fontFamily: Fonts.Poppins_Regular,
            color: Colors.black,
        },
        headerStyle: {
            backgroundColor: Colors.white,
        },
    }
}

  render () {
    return (
      <SafeAreaView style={Style.cointainer}>
        <StatusBar backgroundColor={Colors.white} barStyle='dark-content' />
        <ScrollView showsVerticalScrollIndicator={false} style={{flex:1}}>
        <View
          style={{
            padding: '3%',
            marginTop: '5%',
          }}>
          <View>
            <View style={{flexDirection: 'row'}}>
              <Text style={[Style.label, {width: '50%'}]}>Shift Start</Text>
              <Text style={[Style.label, {width: '50%'}]}>
                24/02/2020 03:20 AM
              </Text>
            </View>
            <View style={{flexDirection: 'row'}}>
              <Text style={[Style.label, {width: '50%'}]}>Shift End</Text>
              <Text style={[Style.label, {width: '50%'}]}>
                25/02/2020 03:20 PM
              </Text>
            </View>
            <View style={{flexDirection: 'row'}}>
              <Text style={[Style.label, {width: '50%'}]}>Generated By</Text>
              <Text style={[Style.label, {width: '50%'}]}>Omar Es-Sudan</Text>
            </View>
            <View style={{flexDirection: 'row'}}>
              <Text style={[Style.label, {width: '50%'}]}>Location At</Text>
              <Text style={[Style.label, {width: '50%'}]}>
                ATL Airport Valet
              </Text>
            </View>
          </View>
          <View style={{marginTop:'7%',}}>
            <View style={{flexDirection: 'row',backgroundColor:Colors.lightButton,padding:'1%'}}>
              <Text style={[Style.label, {width: '70%'}]}>Statistics</Text>
              <Text style={[Style.label, {width: '30%',textAlign:'center'}]}>
                Count
              </Text>
            </View>
            <View style={{flexDirection: 'row',padding:'1%'}}>
              <Text style={[Style.label, {width: '70%'}]}>Starting Vehicles</Text>
              <Text style={[Style.label, {width: '30%',textAlign:'center'}]}>
                3
              </Text>
            </View>
            <View style={{flexDirection: 'row',padding:'1%'}}>
              <Text style={[Style.label, {width: '70%'}]}>Vehicles Received</Text>
              <Text style={[Style.label, {width: '30%',textAlign:'center'}]}>0</Text>
            </View>
            <View style={{flexDirection: 'row',padding:'1%'}}>
              <Text style={[Style.label, {width: '70%'}]}>Vehicles Closed</Text>
              <Text style={[Style.label, {width: '30%',textAlign:'center'}]}>
                0
              </Text>
            </View>
            <View style={{flexDirection: 'row',padding:'1%'}}>
              <Text style={[Style.label, {width: '70%'}]}>Remaining Vehicles</Text>
              <Text style={[Style.label, {width: '30%',textAlign:'center'}]}>
                3
              </Text>
            </View>
          </View>
          <View style= {{flexDirection:'row',justifyContent:'center',borderWidth:1}}>
          <Text style={[Style.label]}>Email To : </Text>
          <Text style={[Style.label,{color:Colors.Theme_color}]}>admin@airportvalet.net</Text>
          </View>
         
         
          <View style={{marginTop:'5%',}}>
          <Text style={Style.label}>Additional Email</Text>
            <TextInput
              underlineColorAndroid={Colors.black}
            />
            <Text style={Style.label}>Notes</Text>
            <TextInput
              underlineColorAndroid={Colors.black}
              multiline={true}
            />
              <TouchableOpacity
            style={[Style.buttonStyle, { width: '100%', marginTop: '10%', },]}>
            <Text style={Style.buttonText}>Email Report</Text>
          </TouchableOpacity>
          </View>
        </View>
        </ScrollView>
      </SafeAreaView>
    )
  }
}
export default ReportView
